name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        run: echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/ssh_key && chmod 600 /tmp/ssh_key

      - name: Determine deployment target
        id: determine-target
        run: |
          backend_target=$(ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "cat /home/ubuntu/backend_target.txt || (echo 'green' > /home/ubuntu/backend_target.txt && cat /home/ubuntu/backend_target.txt)")
          if [ "$backend_target" = "blue" ]; then
            new_target="green"
          else
            new_target="blue"
          fi
          echo "backend_target=$backend_target" >> $GITHUB_OUTPUT
          echo "new_target=$new_target" >> $GITHUB_OUTPUT
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "echo '$new_target' > /home/ubuntu/backend_target.txt"

      - name: Login to Docker Hub on EC2 instance
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "echo '${{ secrets.DOCKERHUB_PW }}' | docker login -u '${{ secrets.DOCKERHUB_USERNAME }}' --password-stdin"

      - name: Pull latest image and deploy new version
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "
            docker pull kfood/kfood:latest
            cd /home/ubuntu
            docker-compose -f /home/ubuntu/korea-food/docker-compose.yml up -d --no-deps \${{ steps.determine-target.outputs.new_target }}
          "

      - name: Health check new environment
        id: health-check
        run: |
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "
            health_url=''
            if [ '${{ steps.determine-target.outputs.new_target }}' = 'blue' ]; then
              health_url='http://${{ secrets.Domain }}:8080/hc'
            else
              health_url='http://${{ secrets.Domain }}:8081/hc'
            fi
            for i in {1..10}; do
              http_status=\$(curl -s -o /dev/null -w '%{http_code}' \$health_url)
              if [ \"\$http_status\" -eq \"200\" ]; then
                echo 'Health check passed!'
                exit 0
              fi
              echo 'Waiting for healthy status...'
              sleep 30
            done
            echo 'Health check failed!'
            exit 1
          "

      - name: Update current file
        if: failure()
        run: |
          backend_target=$(ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "cat /home/ubuntu/backend_target.txt || (echo 'green' > /home/ubuntu/backend_target.txt && cat /home/ubuntu/backend_target.txt)")
          if [ "$backend_target" = "blue" ]; then
            new_target="green"
          else
            new_target="blue"
          fi
          echo "backend_target=$backend_target" >> $GITHUB_OUTPUT
          echo "new_target=$new_target" >> $GITHUB_OUTPUT
          ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "echo '$new_target' > /home/ubuntu/backend_target.txt"


      - name: Update NGINX configuration and reload
        if: success()
        run: |
          ssh -t -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "
            if [ '${{ steps.determine-target.outputs.new_target }}' = 'blue' ]; then
              sed -i 's/server green:8080/server blue:8080/' /home/ubuntu/nginx/nginx.conf
            else
              sed -i 's/server blue:8080/server green:8080/' /home/ubuntu/nginx/nginx.conf
            fi
            docker-compose -f /home/ubuntu/korea-food/docker-compose.yml exec nginx nginx -s reload
          "


      - name: Stop old environment
        if: success()
        run: |
          ssh -t -i /tmp/ssh_key -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -o ConnectTimeout=10 ubuntu@${{ secrets.LIVE_SERVER_IP }} "
            if [ '${{ steps.determine-target.outputs.new_target }}' = 'blue' ]; then
              docker-compose -f /home/ubuntu/korea-food/docker-compose.yml stop green
            else
              docker-compose -f /home/ubuntu/korea-food/docker-compose.yml stop blue
            fi
          "
